INSERT INTO DEPARTMENT (ID, NAME) VALUES
(1, 'Sales'),
(2, 'HR');

--INSERT INTO EMPLOYEE (ID, EMPLOYEE_NO, FIRST_NAME, LAST_NAME, GENDER, BIRTH_DATE, DEPARTMENT_ID, SALARY) VALUES
--;

--INSERT INTO CLIENT (ID, NAME) VALUES
--;

--INSERT INTO ASSIGNMENT (ID, EMPLOYEE_ID, CLIENT_ID, ROLE) VALUES
--;
