name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    if: github.repository == 'Thijsiez/panache-kotlin-dsl'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache --no-daemon
      - uses: softprops/action-gh-release@v2
