name: test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Run tests and publish report to SonarQube
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew koverXmlReport --no-daemon
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew sonar --no-daemon
